@echo off

SET PELICAN=pelican.exe
SET PELICANOPTS=-D

SET BASEDIR=%~dp0
SET INPUTDIR=%BASEDIR%content
SET OUTPUTDIR=%BASEDIR%output
SET CONFFILE=%BASEDIR%pelicanconf.py

%PELICAN% %INPUTDIR% -o %OUTPUTDIR% -s %CONFFILE% %PELICANOPTS%
